### ISSUE TITLE
Composer.json - require is wrong

### ISSUE THREAD

**Issue by GregorDevelopment** [franzholz/patch10011#1]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires jambagecom/patch10011 ^0.4.0 -> satisfiable by jambagecom/patch10011[v0.4.0].
    - jambagecom/patch10011 v0.4.0 requires typo3/cms-core ^9.5,^10.4 -> found typo3/cms-core[dev-master, v8.7.7, ..., 8.7.x-dev, v9.0.0, ..., 9.5.x-dev, v10.0.0, ..., 10.4.x-dev, v11.0.0, ..., 11.3.x-dev (alias of dev-master)] but it does not match the constraint.

in composer.json

`
"require": {    "typo3/cms-core": "^9.5,^10.4"  },
`
needs to be

`"require": {    "typo3/cms-core": "^9.5 || ^10.4"  },`

**Comment by franzholz** [comment]
This is fixed in version 0.4.1.
